eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka/

server:
  port: 8092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-db
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hikari:
        format_sql: true
        show_sql: true